/*$file${.::blinky.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: blinky.qm
* File:  ${.::blinky.c}
*
* This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${.::blinky.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
//===========================================================================
/*$declare${AOs::blinky} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::blinky} ...........................................................*/
typedef struct {
/* protected: */
    QActive super;
} blinky;

/* protected: */
static QState blinky_initial(blinky * const me, void const * const par);
static QState blinky_on(blinky * const me, QEvt const * const e);
static QState blinky_off(blinky * const me, QEvt const * const e);
/*$enddecl${AOs::blinky} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

//===========================================================================
/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.9.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::blinky} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::blinky} ...........................................................*/

/*${AOs::blinky::SM} .......................................................*/
static QState blinky_initial(blinky * const me, void const * const par) {
    /*${AOs::blinky::SM::initial} */
    return Q_TRAN(&blinky_on);
}

/*${AOs::blinky::SM::on} ...................................................*/
static QState blinky_on(blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::blinky::SM::on::TIMEOUT_SIG} */
        case TIMEOUT_SIG_SIG: {
            status_ = Q_TRAN(&blinky_off);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::blinky::SM::off} ..................................................*/
static QState blinky_off(blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::blinky::SM::off::TIMEOUT_SIG} */
        case TIMEOUT_SIG_SIG: {
            status_ = Q_TRAN(&blinky_on);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::blinky} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
