/*$file${.::sm_ui.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: blinky.qm
* File:  ${.::sm_ui.c}
*
* This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${.::sm_ui.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
//===========================================================================
/*$declare${AOs::SM_UI} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::SM_UI} ............................................................*/
typedef struct {
/* protected: */
    QActive super;
} SM_UI;

/* protected: */
static QState SM_UI_initial(SM_UI * const me, void const * const par);
static QState SM_UI_active(SM_UI * const me, QEvt const * const e);
static QState SM_UI_showHelper(SM_UI * const me, QEvt const * const e);
static QState SM_UI_showMain(SM_UI * const me, QEvt const * const e);
/*$enddecl${AOs::SM_UI} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

//===========================================================================
/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.9.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::SM_UI} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::SM_UI} ............................................................*/

/*${AOs::SM_UI::SM} ........................................................*/
static QState SM_UI_initial(SM_UI * const me, void const * const par) {
    /*${AOs::SM_UI::SM::initial} */
    return Q_TRAN(&SM_UI_active);
}

/*${AOs::SM_UI::SM::active} ................................................*/
static QState SM_UI_active(SM_UI * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SM_UI::SM::active::initial} */
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&SM_UI_showMain);
            break;
        }
        /*${AOs::SM_UI::SM::active::UI_TIMER} */
        case UI_TIMER_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::SM_UI::SM::active::UI_KEY_ALT_Q} */
        case UI_KEY_ALT_Q_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::SM_UI::SM::active::UI_BLINKY_TEXT} */
        case UI_BLINKY_TEXT_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::SM_UI::SM::active::UI_KEY_DEBUG} */
        case UI_KEY_DEBUG_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::SM_UI::SM::active::showHelper} ....................................*/
static QState SM_UI_showHelper(SM_UI * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SM_UI::SM::active::showHelper::UI_KEY_ESC} */
        case UI_KEY_ESC_SIG: {
            status_ = Q_TRAN(&SM_UI_showMain);
            break;
        }
        default: {
            status_ = Q_SUPER(&SM_UI_active);
            break;
        }
    }
    return status_;
}

/*${AOs::SM_UI::SM::active::showMain} ......................................*/
static QState SM_UI_showMain(SM_UI * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SM_UI::SM::active::showMain::UI_KEY_CTRL_SLASH} */
        case UI_KEY_CTRL_SLASH_SIG: {
            status_ = Q_TRAN(&SM_UI_showHelper);
            break;
        }
        default: {
            status_ = Q_SUPER(&SM_UI_active);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::SM_UI} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
